config/routes.rb
# coding:utf-8

Rails.application.routes.draw do
  root 'videos#index'

  resources :users do
    # 検索用
    collection do
      get 'search'
    end
  end
  
  resources :messages, except: [:destroy, :update, :edit, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'


  match '/help', to: 'users#help', via: 'get'

  resources :videos do
    resources :comments
    collection do
      get 'search'
    end
  end
  match '/search/:tag', to: 'videos#index', via: 'get', as: :search_tag

  namespace :admin do
    resources :users, :comments, :videos
  end

  resources :favorites, only: [:create, :destroy]

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :video
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @video = Video.find(params[:video_id])
    current_user.favorite!(@video)
  end

  def destroy
    @video = Favorite.find(params[:id]).video
    current_user.unfavorite!(@video)
  end
end

app/views/favorites/_create.html.erb
<%= link_to favorites_path(video_id: video.id), remote: true, method: :post, class: 'favorite-link' do %>
  <i class="fa fa-star-o unfavorite-star">お気に入り登録</i>
<% end %>

app/views/favorites/_destroy.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(video_id: video.id)), remote: true, method: :delete, class: 'favorite-link' do %>
  <i class="fa fa-star favorite-star">お気に入り解除</i>
<% end %>

app/views/favorites/_favorite_btn.html.erb
<% if current_user.favorite?(video) %>
  <%= render 'favorites/destroy', video: video %>
<% else %>
  <%= render 'favorites/create', video: video %>
<% end %>

app/views/favorites/create.js.erb
$('#video_<%= @video.id %>').html('<%= escape_javascript(render("favorites/favorite_btn", video: @video)) %> ');
$('#favorites').text('<%= current_user.favorites.count %>');

app/views/favorites/destroy.js.erb
$('#video_<%= @video.id %>').html('<%= escape_javascript(render("favorites/favorite_btn", video: @video)) %>');
$('#favorites').text('<%= current_user.favorites.count %>');