config/routes.rb
# coding:utf-8

Rails.application.routes.draw do
  root 'videos#index'

  resources :users do
    # 検索用
    collection do
      get 'search'
    end
  end
  
  resources :messages, except: [:destroy, :update, :edit, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'


  match '/help', to: 'users#help', via: 'get'

  resources :videos do
    resources :comments
    collection do
      get 'search'
    end
  end
  match '/search/:tag', to: 'videos#index', via: 'get', as: :search_tag

  namespace :admin do
    resources :users, :comments, :videos
  end

  resources :favorites, only: [:create, :destroy]

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  has_many :videos_categories
  has_many :categories, through: :videos_categories
  has_many :comments
  has_many :favorites
  has_many :favoriting_users, through: :favorites, source: :user

  acts_as_taggable

  # paperclip
  has_attached_file :videofile
  validates_attachment :videofile, content_type: { content_type: ["movie/mp4", "video/mp4", "application/ppt"] }

  validates :user_id,             presence: true,
                                  numericality: { only_integer: true }
  validates :title,               presence: true,
                                  length: { maximum: 255 }
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	before_action :authenticate, only: [:show]
	before_action :set_video, only: [:show, :edit, :update, :destroy]

	def index
		if params[:tag] != nil
			@videos = Video.tagged_with(params[:tag])
		else
			@videos = Video.all
		end
	end

	def search
	end

	def show
		@user_id = current_user.id
	end

	def new
		@video = Video.new
	end

	def create
		@video = Video.new(video_params)
		# ログイン周りがバグってるのでコメントアウト
		@video.user_id = current_user.id
		# @video.user_id = 0
		if @video.save
			redirect_to @video, notice: '投稿が完了しました。'
		else
			render :new
		end
	end

	def edit
	end

	def update
	end

	def destroy
	end

	def tags
		@videos = User.where(tag: params[:tag]).order('count DESC')
	end

	private

	def set_video
		@video = Video.find(params[:id])
	end

	def video_params
		params.require(:video).permit(:code, :title, :videofile, :description, :tag_list)
	end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/favorites.html.erb
<h1>Video</h1>

<%= render @video %>

<h1>Users</h1>

<%= will_paginate @users %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate @users %>

app/views/videos/index.html.erb
<div class="videos">
	<h2>All Movies</h2>
	<% @videos.each do |video| %>
	<div class="wrapper">
		<%= link_to video do %>
		<div class="mask">
			<video src="<%= video.videofile.url %>" preload="metadata">
				お使いのブラウザが動画をサポートしていません。
			</video>
		</div>
		<% end %>
		
		<!-- ユーザーアイコン -->
		<div class="user_icon">
			<% if User.find(video.user_id).avatar? %>
		   <%= link_to (image_tag User.find(video.user_id).avatar.thumb.url, :size => "37x37"), user_path(video.user_id) %>
			 <% else %>
			   <%= link_to (image_tag 'noimage.jpg', :size => "37x37"), user_path(video.user_id) %>
			 <% end %>
		</div>

		<!-- タイトル -->
		<h3><%= link_to video.title, video_path(video.id) %></h3>
		
		<div class="movie_footer">
			<!-- お気に入り数 -->
			<div class="star">
				<%= image_tag 'icons/star.png' %>
				<span><%= Favorite.where(video_id: video.id).count %></span>
			</div>
			<!-- コメント数 -->
			<div class="comment">
				<%= image_tag 'icons/comment.png' %>
				<span><%= Comment.where(video_id: video.id).count %></span>
			</div>

			<!-- 投稿時間 -->
			<div class="time">
				<% time_ago_str = '' %>
				<% if (Time.now - video.created_at).to_i/3600 < 1 %>
				 <% time_ago = ((Time.now - video.created_at).to_i/60).to_s + "m ago" %>
				<% else %>
				 <% time_ago = ((Time.now - video.created_at).to_i/3600).to_s + "h ago" %>
				<% end %>  
				<%= time_ago %>
			</div>
		</div>

	</div>
	<% end %>
</div>

app/views/videos/new.html.erb
<h1>Videos#new</h1>

<div class="row">
  <%= render 'shared/error', obj: @video %>
  <div class="col-md-6 col-md-offset-3 form_margin">
    <%= form_for @video do |f| %>
      <%= f.label :videofile, class: "control-label" %>
      <span>※mp4形式のみ</span>
      <%= f.file_field :videofile %>

      <%= f.label :title, class: "control-label" %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :tag_list, class: "control-label" %>
      <%= f.text_field :tag_list, class: "form-control" %>

      <%= f.label :description, class: "control-label" %>
      <%= f.text_area :description, class: "form-control" %>



      <%= f.submit "投稿", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/videos/show.html.erb
<div class="videos_show">
    <div class="video_wrapper">
        
        <!-- 動画 -->
        <div class="mask">
            <% if @video.videofile %>
            <video controls autoplay>
                <source src='<%= @video.videofile.url %>' type='video/mp4'>
                お使いのブラウザが動画をサポートしていません。
            </video>
            <% end %>
        </div>
        
        <div class="container">
            <!-- タイトル -->
            <h3><%= @video.title %></h3>

            <div class="movie_header">
                <!-- ユーザーアイコン -->
                <% if User.find(@video.user_id).avatar? %>
                    <%= link_to (image_tag User.find(@video.user_id).avatar.thumb.url, :size => "40x40"), user_path(@video.user_id) %>
                <% else %>
                   <%= link_to (image_tag 'noimage.jpg', :size => "40x40"), user_path(@video.user_id) %>
                <% end %>
                
                <div class="right_box">
                    <!-- ユーザー名 -->
                    <p class="name"><%= link_to User.find(@video.user_id).user_name, user_path(@video.user_id) %></span>
                    <!-- 説明文 -->
                    <p class="description"><%= @video.description %></p>
                </div>
            </div>

            <!-- タグ -->
            <ul>
                <% @video.tag_list.each do |t| %>
                <li><%= link_to t,  root_path %></li>
                <% end %>
            </ul>

            <div class="movie_footer">
                <!-- お気に入り数 -->
                <div class="star">
                    <%= image_tag 'icons/star.png' %>
                    <span><%= Favorite.where(video_id: @video.id).count %></span>
                </div>
                <!-- コメント数 -->
                <div class="comment">
                    <%= image_tag 'icons/comment.png' %>
                    <span><%= Comment.where(video_id: @video.id).count %></span>
                </div>

                <!-- 投稿時間 -->
                <div class="time">
                    <% time_ago_str = '' %>
                    <% if (Time.now - @video.created_at).to_i/3600 < 1 %>
                     <% time_ago = ((Time.now - @video.created_at).to_i/60).to_s + "m ago" %>
                    <% else %>
                     <% time_ago = ((Time.now - @video.created_at).to_i/3600).to_s + "h ago" %>
                    <% end %>  
                    <%= time_ago %>
                </div>
            </div>
        </div>
    </div>
    <!-- コメント -->
    <div class="comment_wrapper">
        <h3>Comments</h3>
        <% @video.comments.each do |comment| %>
        <div class="comment_box">
            <!-- ユーザーアイコン -->
            <% if User.find(comment.user_id).avatar? %>
                <%= image_tag User.find(comment.user_id).avatar.thumb.url, :size => "40x40" %>
            <% else %>
               <%= image_tag 'noimage.jpg', :size => "40x40" %>
            <% end %>

            <div class="content">
                <% user_name = User.find_by(id: comment.user_id).user_name %>
                <%= link_to "#{user_name}", user_path(comment.user_id) %>
                <p><%= comment.description %></p>
            </div>
        </div>
        <% end %>

        <!-- 投稿 -->
        <div class="comment">
            <a data-target="con1" class="modal-open"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>コメントする</a>

            <div id="con1" class="modal-content">
              <%= form_for [@video, @video.comments.build], :url => {:controller => 'comments', :action => 'create', :video_id => @video.id, :user_id => @user_id } do |f| %>
            <div style="vertical-align: middle;">
              <%= f.text_area :description, :id => "message-field", :class => "form-control" %>
            </div>
              <%= f.submit "投稿する", class: "btn btn-large btn-primary post_button" %>
              <% end %>
            </div>
        </div>

                <!-- 投稿 -->
        <div class="comment">
        <!-- favorite function test -->
<div id="video_<%= @video.id %>">
    <%= render 'favorites/favorite_btn', video: @video %>
</div> 

        </div>

    </div>
</div>






<!-- favorite function test -->
<!--
<div id="video_<%= @video.id %>">
    <%= render 'favorites/favorite_btn', video: @video %>
</div> 
-->


<script type="text/javascript">
$(function(){
    // スクロールバーの横幅を取得
    $('html').append('<div class="scrollbar" style="overflow:scroll;"></div>');
    var scrollsize = window.innerWidth - $('.scrollbar').prop('clientWidth');
    $('.scrollbar').hide();

    // 「.modal-open」をクリック
    $('.modal-open').click(function(){
        // html、bodyを固定（overflow:hiddenにする）
        $('html, body').addClass('lock');

        // オーバーレイ用の要素を追加
        $('body').append('<div class="modal-overlay"></div>');

        // オーバーレイをフェードイン
        $('.modal-overlay').fadeIn('slow');

        // モーダルコンテンツのIDを取得
        var modal = '#' + $(this).attr('data-target');

         // モーダルコンテンツを囲む要素を追加
        $(modal).wrap("<div class='modal-wrap'></div>");

        // モーダルコンテンツを囲む要素を表示
        $('.modal-wrap').show();

        // モーダルコンテンツの表示位置を設定
        modalResize();

         // モーダルコンテンツフェードイン
        $(modal).fadeIn('slow');

        // モーダルコンテンツをクリックした時はフェードアウトしない
        $(modal).click(function(e){
            e.stopPropagation();
        });

        // 「.modal-overlay」あるいは「.modal-close」をクリック
        $('.modal-wrap, .modal-close').off().click(function(){
            // モーダルコンテンツとオーバーレイをフェードアウト
            $(modal).fadeOut('slow');
            $('.modal-overlay').fadeOut('slow',function(){
                // html、bodyの固定解除
                $('html, body').removeClass('lock');
                // オーバーレイを削除
                $('.modal-overlay').remove();
                // モーダルコンテンツを囲む要素を削除
                $(modal).unwrap("<div class='modal-wrap'></div>");
           });
        });

        // リサイズしたら表示位置を再取得
        $(window).on('resize', function(){
            modalResize();
        });

        // モーダルコンテンツの表示位置を設定する関数
        function modalResize(){
            // ウィンドウの横幅、高さを取得
            var w = $(window).width();
            var h = $(window).height();

            // モーダルコンテンツの横幅、高さを取得
            var mw = $(modal).outerWidth(true);
            var mh = $(modal).outerHeight(true);

            // モーダルコンテンツの表示位置を設定
            if ((mh > h) && (mw > w)) {
                $(modal).css({'left': 0 + 'px','top': 0 + 'px'});
            } else if ((mh > h) && (mw < w)) {
                var x = (w - scrollsize - mw) / 2;
                $(modal).css({'left': x + 'px','top': 0 + 'px'});
            } else if ((mh < h) && (mw > w)) {
                var y = (h - scrollsize - mh) / 2;
                $(modal).css({'left': 0 + 'px','top': y + 'px'});
            } else {
                var x = (w - mw) / 2;
                var y = (h - mh) / 2;
                $(modal).css({'left': x + 'px','top': y + 'px'});
            }
        }

    });
});
</script>

<script type="text/javascript">
    $(document).ready(function() {
        $("#video-tags").tagit();
    });
</script>

<script type="text/javascript">
$("#video-tags").tagit({
    onTagClicked: function(event, ui) {
        // do something special
        console.log(ui.tag);
        var link = '/search/' + ui.tagLabel
        document.location.href = link;
    }
});
</script>