config/routes.rb
# coding:utf-8

Rails.application.routes.draw do
  root 'videos#index'

  resources :users do
    # 検索用
    collection do
      get 'search'
    end
  end
  
  resources :messages, except: [:destroy, :update, :edit, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'


  match '/help', to: 'users#help', via: 'get'

  resources :videos do
    resources :comments
    collection do
      get 'search'
    end
  end
  match '/search/:tag', to: 'videos#index', via: 'get', as: :search_tag

  namespace :admin do
    resources :users, :comments, :videos
  end

  resources :favorites, only: [:create, :destroy]

end

app/views/shared/_error.html.erb
<% unless obj.errors.empty? %>
<div id="errors_explanation">
	<div class="alert alert-danger">
		<p><%= obj.errors.count %> Errors. >></p>
		<ul>
		<% obj.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
</div>
<% end %>

app/views/shared/_error_message.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>*<%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= favorite_user_path(@user) %>">
    <strong id="favorites" class="stat">
      <%= @user.favorite_videos.count %>
    </strong>
  </a>
</div>