config/routes.rb
# coding:utf-8

Rails.application.routes.draw do
  root 'videos#index'

  resources :users do
    # 検索用
    collection do
      get 'search'
    end
  end
  
  resources :messages, except: [:destroy, :update, :edit, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'


  match '/help', to: 'users#help', via: 'get'

  resources :videos do
    resources :comments
    collection do
      get 'search'
    end
  end
  match '/search/:tag', to: 'videos#index', via: 'get', as: :search_tag

  namespace :admin do
    resources :users, :comments, :videos
  end

  resources :favorites, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href='#'>News</a></li>
    </ul>
  </nav>
  <p class="copyright">© 2015 Clanberry - All Right Reserved</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="navbar-inner">
    <div class="container"  id="container">
      <!-- 左側 -->
      <div class="left_box">
        <span class="help"><%= link_to "Help", '#' %></span>
      </div>
      <!-- ロゴ -->
      <div class="logo_box">
        <%= link_to image_tag('logo/logo.png'), root_path %>
      </div>
      <!-- 右側 -->
      <div class="right_box">
        <!-- 検索フィールド -->
        <form class="navbar-form navbar-right" role="search">
            <input type="text" class="form-control" placeholder="Search">
            <%= image_tag('icons/search.png') %>
            <!-- <button type="submit" class="btn btn-default"></button> -->
        </form>

        <!-- ユーザー -->
        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
          <li id="fat-menu" class="dropdown">
            <a href='#' class="dropdown-toggle" data-toggle="dropdown" id="main_btn">
              <%= current_user.user_name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Profile', current_user %></li>
              <li><%= link_to 'Post a Video', new_video_path %></li>
              <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to 'Sign out', signout_path, method: 'delete' %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign in', signin_path, id: "main_btn" %></li>
        <% end %>
      </div>

      
      
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<h2>Categories</h2>
<div class="icons">
	<%= link_to image_tag('categories/chemistry.png', class: "icon"), search_tag_path("chemistry") %>
	<%= link_to image_tag('categories/geography.png', class: "icon"), search_tag_path("geography") %>
	<%= link_to image_tag('categories/electronic.png', class: "icon"), search_tag_path("electronic") %>
	<%= link_to image_tag('categories/mechanic.png', class: "icon"), search_tag_path("mechanic") %>
</div>
<h2>Events</h2>
<div class="events">
	<div class="event_box">
		<%= link_to image_tag('sidebar/event01.jpg', class: "event"), '#' %>
		<div class="text_bg"></div>
		<p>エンジニア必見！次世代型ウェアラブルデバイスRingを使ったハカッソン開催！</p>
	</div>
	<div class="event_box">
		<%= link_to image_tag('sidebar/event02.jpg', class: "event"), '#' %>
		<div class="text_bg"></div>
		<p>アンケートに答えてポイントをゲットしよう！</p>
	</div>
</div>
<h2>Tags</h2>
<div class="tags_array">
  <% ActsAsTaggableOn::Tag.most_used.each do |tag| %>
    <% tags_count = '(' + tag.taggings_count.to_s + ')' %>
    <button class="btn btn-primary tags_index">
      <span class="tags_content"><%= link_to tag.name+tags_count, search_tag_path(tag.name) %></span>
    </button>
  <% end %>
</div>

<div class="events">
  <div class="event_box">
    <%= link_to image_tag('sidebar/ad01.jpg', class: "event"), '#' %>
  </div>
  <div class="event_box">
    <%= link_to image_tag('sidebar/ad02.png', class: "event"), '#' %>
  </div>
    <div class="event_box">
    <%= link_to image_tag('sidebar/ad03.jpg', class: "event"), '#' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CLanberry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>
</head>
<body>
  <div class="header">
  <%= render 'layouts/header' %>
  </div>
  <div class="container" id="container">
    <div class="sidebar">
      <%= render 'layouts/sidebar' %>
    </div>
    <div class="main">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div><!-- end main-->
  </div>
  <%= render 'layouts/footer' %>
  <!--
  <div id="debug">
  <%= debug(params) if Rails.env.development? %>
  </div>
  -->


</body>
</html>